title: Mathematical Economics
author:
  name:  Dr. Peter A Wagner
  email: peter.wagner@york.ac.uk

header_pages:
  # - Downloads.md

# Build settings
remote_theme: just-the-docs

plugins:
 - jekyll-feed
 - jekyll-seo-tag
