title: Mathematical Economics
author:
  name:  Dr. Peter A Wagner
  email: peter.wagner@york.ac.uk

header_pages:
  # - Downloads.md

future: true

show_excerpts: false # set to true to show excerpts on the homepage

# Build settings
remote_theme: pmarsceill/just-the-docs

plugins:
 - jekyll-feed
 - jekyll-seo-tag
